baseURL = "https://movetokube.com/"
languageCode = "en-us"
title = "Move to Kubernetes"
theme = "kube"
description = "Professional Kubernetes migration consultancy services"

googleAnalytics = "UA-129869099-1"

staticDir = ["static"]
[params]
  author = "Tomas Adomavicius"
  description = "Professional Kubernetes migration consultancy services"
[[menu.main]]
    name = "Contact"
    weight = -100
    url = "/contact/"
