only-tags: &only-tags
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: build and push docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t mv2k8s/web:$CIRCLE_TAG .
            docker build -t mv2k8s/web:latest .
            docker push mv2k8s/web:$CIRCLE_TAG
            docker push mv2k8s/web:latest
  deploy:
    docker:
      - image: mv2k8s/kubectl:1.14.1
    steps:
      - run:
          name: update kubernetes deployment
          command: |
            mkdir -p ~/.kube
            echo $KUBECONFIG | base64 -d > ~/.kube/config
            kubectl set image deployment movetokube nginx=mv2k8s/web:$CIRCLE_TAG


workflows:
  version: 2
  # This only runs on deploy tags and not branches
  tagged-build:
    jobs:
      - build: *only-tags
      - deploy:
          <<: *only-tags
          requires:
            - build
