# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: build and push docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t mv2k8s/web:latest .
            docker push mv2k8s/web:latest