apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: movetokube-com
  namespace: movetokube
spec:
  secretName: movetokube-com-tls
  issuerRef:
    name: letsencrypt
  commonName: movetokube.com
  dnsNames:
  - movetokube.com
  - www.movetokube.com
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - movetokube.com
      - www.movetokube.com
