kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: movetokube-com
  namespace: movetokube
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.global-static-ip-name: "movetokube-com"
spec:
  tls:
  - secretName: movetokube-com-tls
  backend:
    serviceName: movetokube-web
    servicePort: 80
