apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: movetokube
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tomas@movetokube.com
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
        - name: prod-dns
          clouddns:
            serviceAccountSecretRef:
              name: clouddns-sa
              key: clouddns-sa.json
            project: kube-229818