apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tomas@movetokube.com
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
        - name: prod-dns
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token